name: Deploy Python Azure Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip Function App
        run: |
          zip -r functionapp.zip . -x "*.git*"

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'crc-function-pycore'
          package: 'functionapp.zip'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

