name: Build and Deploy Node.js Function to Azure (CLI)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install
        working-directory: ./crc-visitor-func

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: crc-function-app
          package: ./crc-visitor-func

      - name: Install Axios for Smoke Test
        run: npm install axios

      - name: Run Smoke Test
        run: node tests/smoke-test.js
